environment:
    matrix:
        # Windows
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          QTDIR: C:\Qt\5.11\msvc2017_64
        # Linux
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          
services:
    - Docker

install:
    # Windows
    - cmd: set PATH=%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
    - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    # Linux
    - sh: sudo service docker start
    
build_script:
    # Windows
    - cmd: qmake Researcher.pro
    - cmd: jom -j %NUMBER_OF_PROCESSORS%
    # Linux
    - sh: docker run -w="/app" -v "$(pwd)":/app rabits/qt:5.11-desktop sudo /opt/Qt/5.11.2/gcc_64/bin/qmake
    - sh: docker run -w="/app" -v "$(pwd)":/app rabits/qt:5.11-desktop sudo make -j 4

after_build:
    # Windows
    - cmd: md Researcher-windows
    - cmd: move release\Researcher.exe Researcher-windows\Researcher.exe 
    - cmd: windeployqt --release --no-translations --no-angle --no-plugins --no-opengl-sw Researcher-windows\Researcher.exe
    - cmd: del Researcher-windows\vcredist*.exe
    - cmd: del Researcher-windows\vc_redist*.exe
    - cmd: xcopy /I %QTDIR%\plugins\platforms\qwindows.dll Researcher-windows\platforms\
    - cmd: 7z a Researcher-windows.zip Researcher-windows\
    # Linux
    - sh: zip -r Researcher-linux.zip Researcher
    
artifacts:
    - path: Researcher-%OS%.zip

deploy:
    provider: GitHub
    description: ''
    auth_token:
        secure: KPKgc2JaeXV8NBnz+72ILmsh7hKA3v7fWYG4D7X4Oxn7zplWJwP/eeWoObEg9YDH
    artifact: Researcher-%OS%.zip
    draft: false
    prerelease: true
    on:
        APPVEYOR_REPO_TAG: true
